--3-1
SELECT *
FROM EMP 
WHERE EMPNO = 7499
AND DEPTNO = 30
;
--3-2
SELECT *
FROM EMP
WHERE DEPTNO = 20
OR JOB = 'SALESMAN'
;
--3-3
SELECT *
FROM EMP
WHERE SAL >= 2500
AND JOB = 'ANALYST'
;
--3-4
SELECT *
FROM EMP
WHERE JOB IN ('CLERK','SALESMAN','MANAGER')
;
--3-5
SELECT *
FROM DEPT
;

SELECT *
FROM EMP
WHERE DEPTNO IN(20,30)
AND JOB = 'MANAGER'
;
--3-6
SELECT *
FROM EMP
WHERE ENAME LIKE '%S'
;
--3-7
SELECT EMPNO,
       ENAME,
       JOB,
       SAL,
       DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN'
;
--3-8
SELECT *
FROM EMP
WHERE SAL BETWEEN 2000 AND 3000
;
--3-9
SELECT ENAME,
       SAL
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000
;
--3-10
SELECT ENAME,
       EMPNO,
       SAL,
       DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND ENAME LIKE '%E%'
AND SAL NOT BETWEEN 1000 AND 2000
;
--3-11
SELECT *
FROM EMP
WHERE COMM IS NULL
AND MGR IS NOT NULL
AND JOB IN ('MANAGER','CLERK')
AND ENAME NOT LIKE '_L%'
;
--3-12
SELECT EMPNO,
       ENAME,
       SAL,
       DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
AND SAL >2000
;
--3-13
SELECT EMPNO,
       ENAME,
       SAL,
       DEPTNO
FROM EMP
WHERE DEPTNO = 20
AND SAL >2000
UNION ALL
SELECT EMPNO,
       ENAME,
       SAL,
       DEPTNO
FROM EMP
WHERE DEPTNO =30
AND SAL >2000
;
--3-14
SELECT *
FROM EMP
WHERE ENAME LIKE '%A%'
;
--3-15
SELECT EMPNO,
       ENAME,
       JOB,
       SAL*12+COMM AS ANNSAL
       FROM EMP
WHERE DEPTNO = 30
AND MGR = 7698
AND COMM IS NOT NULL
AND SAL BETWEEN 1300 AND 1600
ORDER BY EMPNO
;
--3-16
SELECT EMPNO,
       ENAME,
       JOB,
       SAL*12 AS ANNSAL
FROM EMP
WHERE(DEPTNO = 30 AND MGR = 7698)  
OR (DEPTNO = 20 AND JOB = 'ANALYST') 
ORDER BY JOB , ANNSAL DESC
;
--3-17
SELECT EMPNO,
       ENAME,
       JOB,
       SAL*12 AS ANNSAL
FROM EMP
WHERE DEPTNO = 30
AND MGR = 7698
UNION ALL
SELECT EMPNO,
       ENAME,
       JOB,
       SAL*12 AS ANNSAL
FROM EMP
WHERE DEPTNO = 20 
AND JOB = 'ANALYST'
ORDER BY JOB , ANNSAL DESC
;
--3-18
SELECT 'THE'|| DNAME || 'DEPARTMENT IS LOCATED IN' || LOC ||'.'
FROM DEPT
;