--5-1
SELECT SUM(SAL) AS TOT_SAL
        ,  SUM(COMM) AS TOT_COMM
  FROM EMP
;
--5-2
SELECT AVG(SAL) AS SAL_AVG
        ,  AVG(COMM) AS COMM_AVG
  FROM EMP
 WHERE DEPTNO = 30
;
--5-3
SELECT DEPTNO
        ,  ROUND(AVG(SAL),2) AS SAL_AVG
        ,  ROUND(AVG(COMM),2) AS COMM_AVG
  FROM EMP
 GROUP BY DEPTNO
ORDER BY 1
;
--5-4
SELECT DEPTNO
        ,  JOB
        ,  AVG(SAL) AS SAL_AVG
  FROM EMP
GROUP BY DEPTNO
        ,  JOB
HAVING AVG(SAL) >= 500
 ;
--5-5
SELECT ROUND(AVG(SAL),2) AS SAL_AVG
        ,  MAX(SAL) AS MAX_SAL
        ,  MIN(SAL) AS MIN_SAL
        , COUNT(SAL) AS CNT
  FROM EMP
GROUP BY DEPTNO
ORDER BY 1
;
--5-6
SELECT JOB
        ,COUNT(*) AS CNT
  FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3
;

--5-7
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR
     , DEPTNO
     , COUNT(*) AS CNT
  FROM EMP
 GROUP BY TO_CHAR(HIREDATE, 'YYYY')
        , DEPTNO
 ORDER BY 1,2
;
--5-8
SELECT COUNT(COMM) AS "수당을 받는 직원"
        ,  COUNT(*) - COUNT(COMM) AS "수당을 받지 않는 직원"
  FROM EMP
;

--5-9
SELECT EMPNO
        ,  ENAME
        ,  SAL
        ,  DEPTNO
        ,  ROUND(AVG(SAL) OVER(PARTITION BY DEPTNO),2)AS AVG_SAL
  FROM EMP
;
--5-10
SELECT *
  FROM (SELECT DEPTNO , SAL FROM EMP)
  PIVOT(SUM(SAL)
    FOR DEPTNO IN (10 AS "10",
                       20 AS "20",
                       30 AS "30"))
;
--5-11
SELECT SUM(DECODE(DEPTNO, 10, SAL)) AS "10"
     , SUM(DECODE(DEPTNO, 20, SAL)) AS "20"
     , SUM(DECODE(DEPTNO, 30, SAL)) AS "30"
  FROM EMP
;
--5-12
SELECT *
  FROM (SELECT DEPTNO, JOB, SAL
          FROM EMP)
 PIVOT (AVG(SAL)
        FOR JOB IN ('ANALYST' AS ANALYST,
                    'CLERK' AS CLERK,
                    'MANAGER' AS MANAGER,
                    'PRESIDENT' AS PRESIDENT,
                    'SALESMAN' AS SALESMAN))
 ORDER BY DEPTNO
; 

--5-13
SELECT DEPTNO
     , AVG(DECODE(JOB, 'ANALYST', SAL)) AS ANALYST
     , AVG(DECODE(JOB, 'CLERK', SAL)) AS CLERK
     , AVG(DECODE(JOB, 'MANAGER', SAL)) AS MANAGER
     , AVG(DECODE(JOB, 'PRESIDENT', SAL)) AS PRESIDENT
     , AVG(DECODE(JOB, 'SALESMAN', SAL)) AS SALESMAN
  FROM EMP
 GROUP BY DEPTNO  
 ORDER BY 1
;

--5-14
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY ROLLUP(DEPTNO, JOB)
 ORDER BY 1, 2
;

--5-15
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY CUBE(DEPTNO, JOB)
 ORDER BY 1, 2
;

--5-16
SELECT DECODE(GROUPING(DEPTNO), 1, 'ALL_DEPT', DEPTNO) AS DEPTNO
     , DECODE(GROUPING(JOB), 1, 'ALL_JOB', JOB) AS JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY CUBE(DEPTNO, JOB)
 ORDER BY 1,2
;

--5-17
SELECT TO_CHAR(DEPTNO) AS DEPTNO
     , JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY TO_CHAR(DEPTNO)
        , JOB   
UNION ALL        
SELECT TO_CHAR(DEPTNO) AS DEPTNO
     , 'ALL_JOB' AS JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
  GROUP BY TO_CHAR(DEPTNO) 
        , 'ALL_JOB' 
UNION ALL
SELECT 'ALL DEPT' AS DEPTNO
     , JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY 'ALL DEPT'
        , JOB
UNION ALL
SELECT 'ALL DEPT' AS DEPTNO
     , 'ALL JOB' AS JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 ORDER BY 1,2        
;
 
--5-18
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY GROUPING SETS(DEPTNO, JOB)
 ORDER BY 1,2
; 

--5-19
SELECT TO_CHAR(DEPTNO) AS DEPTNO
     , '' AS JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY DEPTNO
        , '' 
UNION ALL
SELECT '' AS DEPTNO
     , JOB
     , ROUND(AVG(SAL), 2) AS AVG_SAL
  FROM EMP
 GROUP BY ''
        , JOB
 ORDER BY 1,2        
;

--5-20
SELECT JOB
     , LISTAGG(ENAME, ',')
       WITHIN GROUP(ORDER BY ENAME) AS ENAMES
  FROM EMP
 GROUP BY JOB
 ORDER BY 1
; 
 